include ../Makefile.kernel
disk:
	$(MAKE) -C build disk

parse:
	$(MAKE) -C build parse

halt:
	$(MAKE) -C build halt

exit:
	$(MAKE) -C build exit

create:
	$(MAKE) -C build create

remove:
	$(MAKE) -C build remove

open:
	$(MAKE) -C build open

close:
	$(MAKE) -C build close

read:
	$(MAKE) -C build read

write:
	$(MAKE) -C build write

fork:
	$(MAKE) -C build fork

exec:
	$(MAKE) -C build exec

wait:
	$(MAKE) -C build wait

other:
	$(MAKE) -C build other

filesys:
	$(MAKE) -C build filesys

project1:
	$(MAKE) -C build project1
